import csv
import time
import os
import logging
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utilities import trim_and_add_hyphens, input_output_folder

best_seller_urls = [
    'https://www.patanjaliayurved.net/product/natural-food-products/noodles/patanjali-atta-noodles-chatpata-family-pack/860',
    'https://www.patanjaliayurved.net/product/natural-food-products/noodles/patanjali-atta-noodles-classic-family-pack/862',
    'https://www.patanjaliayurved.net/product/natural-health-care/ghee/patanjali-cows-ghee/806',
    'https://www.patanjaliayurved.net/product/natural-health-care/chyawanprash/patanjali-special-chyawanprash/708',
    'https://www.patanjaliayurved.net/product/natural-health-care/honey/patanjali-honey/947',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-kachi-ghani-mustard-oil/817',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-sunflower-oil/944',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-fortified-soyabean-oil/932',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-groundnut-oil/963',
    'https://www.patanjaliayurved.net/product/natural-food-products/murabba/patanjali-amla-murabba/739',
    'https://www.patanjaliayurved.net/product/natural-food-products/murabba/divya-gulkand/812',
    'https://www.patanjaliayurved.net/product/natural-food-products/dalia-poha-and-vermicelli/patanjali-dalia/702',
    'https://www.patanjaliayurved.net/product/natural-food-products/dal-pulses/patanjali-soya-chunks/3300',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-lashkari-kolam-rice/1168',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-dubar-basmati-rice/1282',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-dubar-basmati-rice/1438',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-special-basmati-rice/873',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-sona-masoori-rice/1169',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-royal-sona-masoori-rice/1287',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-lashkari-kolam-rice/1388',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-dhanshree-basmati-rice/871',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-samridhhi-basmati-rice/1269',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-super-basmati-rice/864',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-tibar-basmati-rice/1289',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-brown-basmati-rice/898',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-katarani-rice/1288',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-sona-masoori-rice/1406',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-katarani-rice/3291',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-rozana-basmati-rice/868',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-diamond-basmati-rice/3288',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-basmati-rice-silver/1262',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-brown-rice-sona-masoori/1270',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-dhanshree-basmati-rice/1332',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-tibar-basmati-rice/1341',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-gold-basmati-rice/2458',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-basmati-rice-silver/3286',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-shakti-xxl-basmati-rice/869',
    'https://www.patanjaliayurved.net/product/natural-food-products/rice/patanjali-royal-sona-masoori-rice/1401',
    'https://www.patanjaliayurved.net/product/natural-food-products/sugar/patanjali-food-combo-sona-masuri-rice-5kg-arhar-dal-1-kg-bura-1-kg-rs-40-off/3390',
    'https://www.patanjaliayurved.net/product/natural-health-care/diet-food/roasted-diet-roasted-mix-lime/961',
    'https://www.patanjaliayurved.net/product/natural-health-care/diet-food/roasted-diet-flaxseed-black-salt/954',
    'https://www.patanjaliayurved.net/product/natural-health-care/diet-food/roasted-diet-flaxseed-chili-lime/955',
    'https://www.patanjaliayurved.net/product/natural-health-care/diet-food/roasted-diet-melon-n-flaxseed/956',
    'https://www.patanjaliayurved.net/product/natural-health-care/diet-food/roasted-diet-quinoa-masala-flavour/960',
    'https://www.patanjaliayurved.net/product/natural-health-care/diet-food/roasted-diet-rice-crispy-mixture/1480',
    'https://www.patanjaliayurved.net/product/natural-health-care/diet-food/patanjali-roasted-diet-quinoa-puff-masala/3062',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-amla-juice/583',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-aloevera-juice-with-fiber/578',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-lauki-amla-juice/592',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-karela-amla-juice/591',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-giloy-amla-juice/587',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-arjun-amla-juice-l/586',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-amla-juice/582',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-aloevera-juice-with-fiber-and-orange-flavour/579',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-gulab-sharbat/783',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-bel-sharbat/781',
    'https://www.patanjaliayurved.net/product/natural-health-care/health-drinks/patanjali-brahmi-sharbat/782',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/patanjali-saundarya-aloe-vera-gel/546',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-aloevera-gel-face-wash/3866',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-aloe-vera-gel-kesar-chandan/547',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-aloe-vera-gel/545',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-aloe-vera-gel/2223',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/aloevera-gel-kchandan-combo-for-face-skin-hair-150-mlpack-of-2-rs-20-off/3362',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/combo-saundarya-aloe-vera-gel-kesar-chandan-60-mlaloevera-moisturizing-cream-50gm-rs-12-off/3333',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-orange-aloevera-face-wash/662',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-aloe-vera-gel-kesar-chandan/885',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/aloevera-gel-combo-for-face-skin-hair-150-mlpack-of-2-rs-18-off/3361',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-dental-cream-junior/752',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-medicated-toothpaste/753',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/tooth-powder-manjan/divya-dant-manjan/37',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-dental-cream-advance/1292',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-natural-toothpaste/749',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/dant-kanti-natural-18g-r10-to-16-sachet/3994',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/patanjali-advanced-dant-kanti-manjan/870',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-aloevera-gel-toothpaste/937',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-natural-toothpaste/748',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-natural-toothpaste/3951',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-natural-toothpaste-value-pack/3987',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/patanjali-dant-kanti-natural-toothpaste/4085',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/dant-kanti-natural-toothpaste-new/3986',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-dental-cream-advance/751',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/patanjali-dant-kanti-dental-cream-adv-2x100-g/990',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/dant-kanti-natural200gx3-big-saver-pack/3593',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/dant-kanti-sensitive-tp-50gx3-disp-pack/3744',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-natural-family-value-pack/923',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-red-toothpaste/1008',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-fresh-active-gel/1042',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-fresh-active-gel/1342',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/tooth-brush/patanjali-dant-kanti-kids-gentle-toothbrush/3587',
    'https://www.patanjaliayurved.net/product/natural-personal-care/dental-care/toothpaste/patanjali-dant-kanti-red-toothpaste/1354',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/kesh-kanti-advance-herbal-hair-expert-shampoo/3949',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-milk-protein-hair-cleanser/1153',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-anti-dandruff-hair-cleanser/3922',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-natural-hair-cleanser/889',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-hair-cleanser-silk-shine/1298',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-natural-hair-cleanser/3919',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/keshkanti-hair-cleanser-natural/3989',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-hair-cleanser-silk-shine/1014',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-milk-protein-hair-cleanser/3920',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-reetha-hair-cleanser/3923',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-shikakai-hair-cleanser/3924',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/conditioner/kesh-kanti-combo-conditioner-protein-100-mlhair-cleanser-a-dandruff-450-ml-rs-30-off/3375',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/kesh-kanti-combo-kesh-kanti-natural-hair-cleanser-450-mlkesh-kanti-hair-oil-120-ml-rs-30-off/3376',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/patanjali-kesh-kanti-hair-cleanser-aloevera/3925',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/shampoo/keshkanti-hair-cleanser-aloevera/3990',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-amla-hair-oil/888',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-sarson-amla-hair-oil/3904',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-hair-oil/542',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-almond-hair-oil/1283',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-almond-hair-oil/540',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-amla-hair-oil/541',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-hair-oil/544',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-amla-hair-oil/946',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-almond-hair-oil/3267',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-sheetal-hair-oil/1338',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-sheetal-hair-oil/832',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/haircare-combo-amla-hair-oil-200-mlconditioner-damage-control-100-ml-rs-14-off/3337',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/combo-kesh-kanti-hair-oil-300-ml-pack-of-2-rs-50-off/3342',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/combo-hebal-mehandi-100-gm-amla-hair-oil-200-ml-rs-10-off/3340',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-advance-herbal-hair-expert-oil/3541',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-kesh-kanti-advance-herbal-hair-expert-oil/3892',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-coconut-oil-j/918',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/patanjali-walnut-oil/3997',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-virgin-coconut-oil/1013',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-virgin-coconut-oil/1137',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-coconut-oil-j/1322',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-coconut-oil/802',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-coconut-oil/4077',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/almond-hair-care-combo-almond-oil-200-mlhair-condioner-olive-almond-100-ml-rs-15-off/3338',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/haircare-combo-amla-hair-oil-200-mlconditioner-damage-control-100-ml-rs-14-off/3337',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/hair-oil/combo-kesh-kanti-hair-oil-300-ml-pack-of-2-rs-50-off/3342',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/combo-hebal-mehandi-100-gm-amla-hair-oil-200-ml-rs-10-off/3340',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/kesh-kanti-combo-kesh-kanti-herbal-mehandi-100-gmkesh-kanti-hair-oil-300ml-rs-30-off/3360',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/natural-coconut-oil-combo-virgin-coconut-oil-500ml-brown-basmati-rice-jar-1kg-rs-50-off/3374',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-sesame-oil-b/1737',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/100-pure-virgin-coconut-oil-500ml-combo-pack-of-2-rs-65-off/3372',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/patanjali-100-pure-virgin-coconut-oil-250ml-combo-pack-of-2-rs-35-off/3373',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/combo-fortified-soyabean-oil-1-ltr-bpack-of-2-rs-15-off/3328',
    'https://www.patanjaliayurved.net/product/natural-food-products/edible-oil/combo-coconut-oil-500-mlpack-of-2-rs-30-off/3339',
    'https://www.patanjaliayurved.net/product/natural-personal-care/hair-care/patanjali-kesh-kanti-herbal-mehandi-burgundy/3280',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-honey-orange-face-wash/659',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-rose-face-wash/663',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/mens-charcoal-active-face-wash/3763',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/mens-energy-active-face-wash/3764',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/mens-beard-entice-face-wash/3765',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-aloevera-gel-face-wash/3866',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-neem-tulsi-face-wash/661',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-face-wash/665',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-face-wash/4114',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-orange-aloevera-face-wash/662',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-lemon-honey-face-wash/660',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-face-wash-aloevera-neem-tulsi-orange-peel/1005',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/patanjali-saundarya-neem-tulsi-face-wash/1123',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/combo-saundarya-neem-face-wash-60ml-pack-of-2-rs-8-off/3329',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/combo-rose-face-wash-60-gmpack-of-2-rs-8-off/3331',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/face-wash/combo-honey-orange-face-wash-60-gmpack-of-2-rs-8-off/3332',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/beauty-combo-saundarya-face-wash-60mlneem-aloevera-with-cucumber-face-pack-60gmapricot-face-scrub-60gmbeauty-cream-50-gm-rs-25-off/3330',
    'https://www.patanjaliayurved.net/product/natural-personal-care/skin-care/nourishing-body-combo-body-ubtan-100-gmrose-face-wash-60-mlmoisturizer-cream-50-gm-apricot-face-scrub-60-gm-rs-25-off/3371',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-multani-mitti-body-cleanser/565',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/aloevera-kanti-body-cleanser-monthly-pack/3862',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-lemon-body-cleanser/562',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-aloevera-kanti-body-cleanser/570',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-aloevera-kanti-body-cleanser/3898',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-aloevera-kanti-body-cleanser-pack-of-4/3901',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-lime-fresh-body-cleanser/3859',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-mogra-body-cleanser/4072',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-neem-kanti-body-cleanser-4x1-45-gm/3779',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-saundarya-sandal-body-cleanser/568',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-rose-body-cleanser/566',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/neem-kanti-body-cleanser-monthly-pack/3860',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/haldi-chandan-kanti-body-cleanser-monthly-pack/3861',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/saundarya-honey-kesar-body-cleanser/3993',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-neem-kanti-body-cleanser/1028',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-aloevera-kanti-body-cleanser/571',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-kanti-panchagavya-body-cleanser/574',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-neem-kanti-body-cleanser/573',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-neem-kanti-body-cleanser/3778',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-neem-kanti-body-cleanser/3900',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-neem-kanti-body-cleanser-pack-of-4/3903',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/neem-kanti-body-cleanser-75-g-pack-of-4/4078',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/haldi-chandan-kanti-body-cleanser4x1-45gm/3777',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-haldi-chandan-kanti-body-cleanser/561',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-kanti-panchagavya-body-cleanser/1029',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/haldi-chandan-kanti-body-cleanser/3776',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-haldi-chandan-kanti-body-cleanser/3899',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-haldi-chandan-kanti-body-cleanser-pack-of-4/3902',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-aloevera-kanti-body-cleanser-4x1-75-g/991',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/aloevera-kanti-body-cleanser-4x145-gm/3775',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-aquafresh-body-cleanser/4074',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-haldi-chandan-kanti-body-cleanser/572',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-lemon-body-cleanser-125g-co-b3g1-free/3493',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-mint-tulsi-body-cleanser/4073',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-haldi-chandan-kanti-body-cleanser-4x1-75-g/940',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-rose-body-cleanser/3275',
    'https://www.patanjaliayurved.net/product/natural-personal-care/body-care/patanjali-rose-body-cleanser-125g-co-b3g1-free/3567',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-amla-candy/603',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-amla-candy/1186',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-bel-candy/605',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-bel-candy/1302',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-amla-chatpata-candy/1654',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-amla-chatpata-candy/604',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-ginger-candy/981',
    'https://www.patanjaliayurved.net/product/natural-food-products/candy/patanjali-hikick-candy-kacha-aam-jar/3406',
    ]

def process_input_file():
    input_file_path = os.path.join(input_output_folder(), 'patanjali-ayurved-scrape.csv')
    with open(input_file_path, 'r') as file:
        reader = csv.DictReader(file)
        rows = list(reader)
        logging.info(f"Number of rows in input file: {len(rows)}")
        
        for row in rows:
            url = row['url']
            last_breadcrumb = trim_and_add_hyphens(row['lastbreadcrumb'])
            heading = row['cleaned-heading']
            description = row['product-information']
            sizes = row['variants'].split(',') if 'variants' in row else [''] 
            images = row['product-image'].split(',') if 'product-image' in row else ['']
            tags = row['Tags']
            if url in best_seller_urls:
                tags += ',best-seller'

            for index, (size, image) in enumerate(zip(sizes, images)):
                item = process_row(url, last_breadcrumb, heading, description, size.strip(), image.strip(), index+1, tags)
                yield item

def process_row(url, last_breadcrumb, heading, description, size, image, image_position, tags):
    item = {
        'Product Id': '',
        'Variant Id': '',
        'Handle': last_breadcrumb,
        'Title': heading,
        'Body (Html)': description,
        'Vendor': 'Patanjali',
        'Type': '',
        'Tags': tags,
        'Published': 'TRUE',
        'Option Fulfill Value': '',
        'Custom Option': '[]',
        'Option1 Name': 'Size',	
        'Option1 Value': size,
        'Option2 Name': '',	
        'Option2 Value': '',
        'Option3 Name': '',	
        'Option3 Value': '',
        'Variant Sku': '',
        'Variant Grams': '',
        'Variant Inventory Tracker': '',
        'Variant Inventory Qty': '',
        'Variant Inventory Policy': 'continue',
        'Variant Fulfillment Service': 'manual',
        'Variant Price': '0',
        'Variant Compare At Price': '0',
        'Variant Requires Shipping': 'true',
        'Variant Taxable': 'TRUE',
        'Variant Barcode': '',
        'Image Src': image,
        'Image Position': image_position,
        'Image Alt Text': heading,
        'Gift Card': '',
        'Google Shopping / Mpn': '',
        'Google Shopping / Age Group': '',
        'Google Shopping / Gender': '',
        'Google Shopping / Google Product Category': '',
        'Seo Title': '',
        'Seo Description': '',
        'Google Shopping / Adwords Grouping': '',
        'Google Shopping / Adwords Labels': '',
        'Google Shopping / Condition': '',
        'Google Shopping / Custom Product': '',
        'Google Shopping / Custom Label 0': '',
        'Google Shopping / Custom Label 1': '',
        'Google Shopping / Custom Label 2': '',
        'Google Shopping / Custom Label 3': '',
        'Google Shopping / Custom Label 4': '',
        'Variant Image': '',
        'Variant Weight Unit': '',
        'Variant Tax Code': '',
        'Cost Per Item': '',
        'Available On Listing Pages': 'TRUE',
        'Available On Sitemap Files': 'TRUE',
        'Template': '',
        'Shipping Profile Name': '',
        'Variant Tag': '',
        'Facebook Pixel Id': '',
        'Facebook Access Token': '',
        'Product Stock Status': '',
        'Shipping Fee': '',
        'Base Cost Variant': ''
    }
    return item
#https://help.shopbase.com/en/article/import-products-to-shopbase-by-csv-file-s0aqya/
def generate_output_file():
    start_time = time.time()
    output_file_path = f'{input_output_folder()}/shopbase-import.csv'
    rows_processed = 0

    with open(output_file_path, 'w', newline='') as file:
        fieldnames = [
            'Product Id', 'Variant Id', 'Handle', 'Title', 'Body (Html)', 'Vendor', 'Type', 'Tags', 'Published',
            'Option Fulfill Value', 'Custom Option', 'Option1 Name', 'Option1 Value', 'Option2 Name', 'Option2 Value',
            'Option3 Name', 'Option3 Value', 'Variant Sku', 'Variant Grams', 'Variant Inventory Tracker',
            'Variant Inventory Qty', 'Variant Inventory Policy', 'Variant Fulfillment Service', 'Variant Price',
            'Variant Compare At Price', 'Variant Requires Shipping', 'Variant Taxable', 'Variant Barcode',
            'Image Src', 'Image Position', 'Image Alt Text', 'Gift Card', 'Google Shopping / Mpn',
            'Google Shopping / Age Group', 'Google Shopping / Gender', 'Google Shopping / Google Product Category',
            'Seo Title', 'Seo Description', 'Google Shopping / Adwords Grouping', 'Google Shopping / Adwords Labels',
            'Google Shopping / Condition', 'Google Shopping / Custom Product', 'Google Shopping / Custom Label 0',
            'Google Shopping / Custom Label 1', 'Google Shopping / Custom Label 2', 'Google Shopping / Custom Label 3',
            'Google Shopping / Custom Label 4', 'Variant Image', 'Variant Weight Unit', 'Variant Tax Code',
            'Cost Per Item', 'Available On Listing Pages', 'Available On Sitemap Files', 'Template',
            'Shipping Profile Name', 'Variant Tag', 'Facebook Pixel Id', 'Facebook Access Token', 'Product Stock Status',
            'Shipping Fee', 'Base Cost Variant'
        ]
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()

        for item in process_input_file():
            writer.writerow(item)
            rows_processed += 1

    execution_time = time.time() - start_time
    logging.info(f"Script execution time: {execution_time} seconds")
    logging.info(f"Number of rows processed: {rows_processed}")

generate_output_file()